In [0]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set() # 그래프 색상이 좀더 풍부해짐


## Iris 데이터: 3가지 종류의 붓꼿 데이터가 50개씩 순서대로 저장되어 있음


In [1]:
from sklearn import datasets
iris = datasets.load_iris()
 
print(iris.feature_names)
print(iris.target_names)

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
['setosa' 'versicolor' 'virginica']


In [2]:
print(iris.data[:5])
print(iris.target[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
[0 0 0 0 0]


In [0]:
list(iris.target_names)

In [3]:
print(iris.data[50:55])
print(iris.target[50:55])

[[7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.9 1.5]
 [5.5 2.3 4.  1.3]
 [6.5 2.8 4.6 1.5]]
[1 1 1 1 1]


In [4]:
print(iris.data[100:105])
print(iris.target[100:105])

[[6.3 3.3 6.  2.5]
 [5.8 2.7 5.1 1.9]
 [7.1 3.  5.9 2.1]
 [6.3 2.9 5.6 1.8]
 [6.5 3.  5.8 2.2]]
[2 2 2 2 2]


### np - 칼럼 합치기

In [7]:
merged = np.c_[iris.data, iris.target]
print(merged.shape)
print(merged[:10])

(150, 5)
[[5.1 3.5 1.4 0.2 0. ]
 [4.9 3.  1.4 0.2 0. ]
 [4.7 3.2 1.3 0.2 0. ]
 [4.6 3.1 1.5 0.2 0. ]
 [5.  3.6 1.4 0.2 0. ]
 [5.4 3.9 1.7 0.4 0. ]
 [4.6 3.4 1.4 0.3 0. ]
 [5.  3.4 1.5 0.2 0. ]
 [4.4 2.9 1.4 0.2 0. ]
 [4.9 3.1 1.5 0.1 0. ]]


### numpy에서 칼럼간 correlation 구하기


In [8]:
np.corrcoef(merged, rowvar=False) # rowvar=False로 해야 칼럼간 관계구함. 아니면 행간의 관계구함.

array([[ 1.        , -0.11756978,  0.87175378,  0.81794113,  0.78256123],
       [-0.11756978,  1.        , -0.4284401 , -0.36612593, -0.42665756],
       [ 0.87175378, -0.4284401 ,  1.        ,  0.96286543,  0.9490347 ],
       [ 0.81794113, -0.36612593,  0.96286543,  1.        ,  0.95654733],
       [ 0.78256123, -0.42665756,  0.9490347 ,  0.95654733,  1.        ]])

## pandas DataFrame으로 변환하기

In [9]:
df = pd.DataFrame(np.c_[iris.data, iris.target])
df.describe()

0           1           2           3           4
count  150.000000  150.000000  150.000000  150.000000  150.000000
mean     5.843333    3.057333    3.758000    1.199333    1.000000
std      0.828066    0.435866    1.765298    0.762238    0.819232
min      4.300000    2.000000    1.000000    0.100000    0.000000
25%      5.100000    2.800000    1.600000    0.300000    0.000000
50%      5.800000    3.000000    4.350000    1.300000    1.000000
75%      6.400000    3.300000    5.100000    1.800000    2.000000
max      7.900000    4.400000    6.900000    2.500000    2.000000

### pandas에서 칼럼간 correlation 구하기




In [10]:
df.corr()

0         1         2         3         4
0  1.000000 -0.117570  0.871754  0.817941  0.782561
1 -0.117570  1.000000 -0.428440 -0.366126 -0.426658
2  0.871754 -0.428440  1.000000  0.962865  0.949035
3  0.817941 -0.366126  0.962865  1.000000  0.956547
4  0.782561 -0.426658  0.949035  0.956547  1.000000

## 칼럼을 선택적으로 사용하기

In [11]:
import numpy as np
from sklearn import datasets
iris = datasets.load_iris() # IRIS 데이터를 로딩
print(iris.feature_names)
print(iris.feature_names[2])
print(iris.feature_names[3])
X = iris.data[:, [2,3]] # 0~3번 칼럼중에 2,3번 칼럼만 이용하는 것임.
Y = iris.target

['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
petal length (cm)
petal width (cm)


In [0]:
print(X[:5])
print(Y[:5])